# Generated by Django 3.2.4 on 2021-06-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwertyindex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qwertyindex',
            name='github_project_url',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qwertyindex',
            name='github_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
