# Generated by Django 3.2.4 on 2021-06-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qwertyindex', '0003_subscibemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qwertyindex',
            name='description',
        ),
        migrations.RemoveField(
            model_name='qwertyindex',
            name='image',
        ),
        migrations.RemoveField(
            model_name='qwertyindex',
            name='title',
        ),
    ]
